### ISSUE TITLE
Intrinsics

### ISSUE THREAD

**Issue by freesig** [essential-contributions/pint#571]
# Missing Intrinsics
There will be more coming as we work out some more design but these are the current missing intrinsics.
The syntax is just a suggestion. I'll leave the actual syntax design up to you.
## Mutable Key Length
Puts the number of keys that are being proposed as mutable for this intent on the stack.
**Type**
```
() -> int
```
**Proposed syntax**
```
context::storage::keys::len()
```
**ASM**
```yaml
MutKeysLen:
  stack_out: [len]
```
## Mutable Keys Contains
Puts a `true` on the stack if the key is contained within the set of currently proposed keys.
**Type**
*Not sure if `int` is right here as a key is just a list of arbitrary `Word`s.
```
int[int] -> bool
```
**Proposed syntax**
```
context::storage::contains(key);
```
**ASM**
*This is a proposed op but should land by next week.*
```yaml
MutKeysContains:
  stack_in:
    elem: key
    len: key_num_words
  stack_out: [bool]
```
## Address
Puts the content hash of the `set of intents` **and** the content hash of `the current intent` on the stack.
**Type**
```
() -> { b256, b256 }
```
**Proposed syntax**
```
context::address()
```
**ASM**
```yaml
ThisSetAddress:
  stack_out: [key_0, key_1, key_2, key_3]
ThisAddress:
  stack_out: [key_0, key_1, key_2, key_3]
```
## Set Address
Puts the content hash of the `set of intents` on the stack.
**Type**
```
() -> b256
```
**Proposed syntax**
```
context::set_address()
```
**ASM**
```yaml
ThisSetAddress:
  stack_out: [key_0, key_1, key_2, key_3]
```
## Intent Address
Puts the content hash of `the current intent` on the stack.
**Type**
```
() -> b256
```
**Proposed syntax**
```
context::intent_address()
```
**ASM**
```yaml
ThisAddress:
  stack_out: [key_0, key_1, key_2, key_3]
```
## Pathway
Puts the pathway of the current intent on the stack.
**Type**
```
() -> int
```
**Proposed syntax**
```
context::pathway()
```
**ASM**
*This is a proposed op but should land by next week.*
```yaml
ThisPathway:
  stack_out: [int]
```
## Instance
Puts the content hash of the `set of intents` **and** the content hash of `the current intent` **and** the pathway of the current intent on the stack.
**Type**
```
() -> { b256, b256, int }
```
**Proposed syntax**
```
context::instance()
```
**ASM**
*This is a proposed op but should land by next week.*
```yaml
ThisSetAddress:
  stack_out: [key_0, key_1, key_2, key_3]
ThisAddress:
  stack_out: [key_0, key_1, key_2, key_3]
ThisPathway:
  stack_out: [int]
```
## Sha256
Pops data off the stack and hashes it, then puts the hash on the stack.
**Type**
*I'm not sure what type to give `T` as we should be able to hash anything as a list of words on the stack.*
```
T[int] -> b256
```
**Proposed syntax**
```
sha256(data);
```
**ASM**
```yaml
Sha256:
  stack_in: [data, data_len]
  stack_out: [hash_w0, hash_w1, hash_w2, hash_w3]
```
## Verify Ed25519
Pops data, signature and public key off the stack and verifies the signature then pushes the result onto the stack.
**Type**
```
(b256, {b256, b256}, b256) -> bool
```
**Proposed syntax**
```
let public_key: b256;
let signature: { b256, b256 };
verify_ed25519(public_key, signature, sha256(data));
```
**ASM**
```yaml
VerifyEd25519:
  stack_in: [data, data_len, sig_w0, sig_w1, sig_w2, sig_w3, sig_w4, sig_w5, sig_w6, sig_w7, key_w0, key_w1, key_w2, key_w3]
  stack_out: [bool]
```
## Recover Secp256k1
Pops data and signature off the stack and recovers the public key then pushes the public key onto the stack. This also verifies the message.
*Note that the sizes of the public key and signature both require an extra word. Public key is 5 words and signature is 9 words.*
**Type**
```
({ b256, b256, int }, b256) -> { b256, int }
```
**Proposed syntax**
```
let public_key: { b256, int };
let signature: { b256, b256, int };
recover_secp256k1(signature, sha256(data)) == public_key;
```
**ASM**
The returned key will be `[0, 0, 0, 0, 0]` if the recovery fails.
*This is a proposed op but should land by next week.*
```yaml
RecoverSecp256k1:
  stack_in: [hash_0, hash_1, hash_2, hash_3, sig_w0, sig_w1, sig_w2, sig_w3, sig_w4, sig_w5, sig_w6, sig_w7, sig_8]
  stack_out: [key_w0, key_w1, key_w2, key_w3, key_w4]
```
## State Is Some
Pops a slot and delta off the stack and pushes `true` if the state is some.
**Type**
*`T` is any type that is a state variable.*
```
T -> bool
```
**Proposed syntax**
```
state foo: int = storage::foo[key];
is_some(foo);
```
**ASM**
```yaml
StateIsSome:
  stack_in: [slot, delta]
  stack_out: [bool]
```
