### ISSUE TITLE
Add support for specifying salt for `[contract-dependencies]`

### ISSUE THREAD

**Issue by mitchmindtree** [essential-contributions/pint#931]
It should be possible to optionally specify a salt for contract dependencies in the `[contract-dependencies]` table entries. E.g.

```toml
[contract-dependencies]
foo = { path = "/path/to/foo", salt = "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF" }
```
